What happened to the function that ran away? "It never returned"
